### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by alivanov** [an-rahulpandey/ios-audio-picker#1]
Hi Rahul,
thanks for the plugin!

Getting this exceptions after selecting a song:
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* setObjectForKey: object cannot be nil (key: image)'

I'm not an expert in Objective-C, but I guess it is because of this line of code (/src/ios/iOSAudioPicker.m):
[songInfo setObject:[imgData base64EncodedString] forKey:@"image"];

Could you please avoid nil values along the songInfo object?

Thanks in advance,
Alex

**Comment by an-rahulpandey** [comment]
Hello alivano,
Thanks for pointing out the issue.
I will take a look into this as soon as possible.
