### ISSUE TITLE
Build error re: base64EncodedString

### ISSUE THREAD

**Issue by smartyw** [an-rahulpandey/ios-audio-picker#10]
/Users/martin/myapp/platforms/ios/My App/Plugins/me.rahul.plugins.audio-picker/iOSAudioPicker.m:164:58: error: no
      visible @interface for 'NSData' declares the selector 'base64EncodedString'
                            [songInfo setObject:[imgData base64EncodedString] forKey:@"image"];
                                                 ~~~~~~~ ^~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by an-rahulpandey** [comment]
Hi,
Please try this plugin - https://github.com/an-rahulpandey/cordova-plugin-mediapicker

**Comment by smartyw** [comment]
Thanks but I already did and it doesn't work for me. I posted this issue: https://github.com/an-rahulpandey/cordova-plugin-mediapicker/issues/10
