### ISSUE TITLE
Can't play selected file

### ISSUE THREAD

**Issue by markbrown4** [an-rahulpandey/ios-audio-picker#3]
Hey Rahul,

I haven't found a way to be able to play the selected audio yet, I have tried loading the **exportedurl** and **ipodurl** returned from the picker with the Media object but both throw errors.

``` javascript
window.plugins.iOSAudioPicker.getAudio(function(songs) {
  var song = {
    ipodurl: songs[0].ipodurl
    artist: songs[0].artist
    exportedurl: songs[0].exportedurl
    title: songs[0].title
  };

  var media = new Media(song.exportedurl, function() {
    console.log('huzzah');
  }, function(e) {
    console.log(e);
  })

}, function() {
  console.log('error picking audio');
},'false','false')
```

Cannot use audio file from resource 'ipod-library://item/item.m4a?id=1535644640347967362
Cannot use audio file from resource 'file:///var/mobile/Containers/Data/Application/7524217E-4ABF-4395-A801-1C1ADB468FBD/Documents/Babys.m4a'

Also tried removing "file://" which was suggested elsewhere
Cannot use audio file from resource '/var/mobile/Containers/Data/Application/7524217E-4ABF-4395-A801-1C1ADB468FBD/Documents/Babys.m4a'

**Comment by an-rahulpandey** [comment]
Hi,

Did you check the demo folder? 
I think this is what you should try - 

```
var fileurl = data[i].exportedurl;
var src = fileurl.replace("file:///","/");
src = decodeURI(fileurl);
var my_media = new Media(src, onSuccess, onError);

 // Play audio
 my_media.play();
```

**Comment by markbrown4** [comment]
Thanks for the reply, yes you're right.

The problem was I didn't realise the paths changed with every build, so every time I tested on the device the paths would break.

I've ended up finding the deviceRoot on load and then using that to locate the selected files.

``` coffeescript
window.requestFileSystem LocalFileSystem.PERSISTENT, 0, (fileSystem)->
  window.deviceRoot = decodeURIComponent(fileSystem.root.toURL().replace('file://', ''))
, ->
  console.log 'requestFileSystem error'
```

`deviceRoot + song.filename`

I didn't check the demo file, might be worth throwing a full example into the readme.

**Comment by an-rahulpandey** [comment]
Hi,
Glad to know you solved the problem. When I worked on the plugin, I didn't need the File plugin.
Do you really need the file plugin to play the song?

**Comment by an-rahulpandey** [comment]
When I worked on the plugin, I didn't need the File plugin. I just used the JavaScript to replace the file:// or file://localhost/ from the path.
May be I need to look again, there might be some changes or update.

**Comment by markbrown4** [comment]
You're right, the demo still works fine without knowing the `fileSystem.root`

I needed it because I was caching the picked audio in localStorage, every time I built on the device the root path would change breaking the paths.
