### ISSUE TITLE
Son not playing

### ISSUE THREAD

**Issue by cinder92** [an-rahulpandey/ios-audio-picker#9]
Hello thanks for your plugin, everything is working like a charm except playing song, cordova media still saying -1 in _duration property (that means that my file does not exist) any idea about this?

in Path property i delete "file://" and still does not work.

thanks!

**Comment by an-rahulpandey** [comment]
Do not use the demo html for playing the song, it needs update. Use the cdvfile protocol to play the song. Please see here - 

https://github.com/apache/cordova-plugin-media#media
https://github.com/apache/cordova-plugin-file
